version: 2
updates:
  # bundle major updates monthly
  - package-ecosystem: npm
    # explicitly set target branch to allow two npm configs
    # https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    target-branch: canary
    directory: /
    open-pull-requests-limit: 5
    schedule:
      interval: monthly
    commit-message:
      prefix: feat(deps)!
      include: scope
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  # bundle minor and patch updates daily
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 5
    schedule:
      interval: daily
    commit-message:
      prefix: chore(deps)
      include: scope
    groups:
      patch-updates:
        update-types:
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
