name: Auto-merge Dependabot PRs

on:
  pull_request_target:
    branches:
      - canary

jobs:
  wait-for-checks:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Wait for status checks
        uses: poseidon/wait-for-status-checks@899c768d191b56eef585c18f8558da19e1f3e707 # v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  dependabot:
    if: github.actor == 'dependabot[bot]'
    needs: wait-for-checks

    runs-on: ubuntu-latest

    steps:
      - name: Generate access token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          # ensure branches share histories
          # see: https://github.com/actions/checkout/issues/125
          fetch-depth: 0

      - name: Fetch Dependabot metadata
        id: dependabot_metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR
        if: |
          steps.dependabot_metadata.outputs.update-type == 'version-update:semver-minor' ||
          steps.dependabot_metadata.outputs.update-type == 'version-update:semver-patch'
        run: |
          git config --global user.name "${{ vars.RELEASE_USER_NAME }}"
          git config --global user.email "${{ vars.RELEASE_USER_EMAIL }}"
          git fetch --all
          git fetch . "origin/${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.head.ref }}"
          git merge --ff-only "origin/${{ github.event.pull_request.head.ref }}"
          git push origin "${{ steps.dependabot_metadata.outputs.target-branch }}"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
