name: Comment on new pull request

on:
  pull_request_target:
    types: [opened]
    branches:
      - main
      - canary

jobs:
  comment_on_new_pr:
    name: Comment on new pull request
    runs-on: ubuntu-latest

    steps:
      - name: Generate access token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Add comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const { commentOnNewPr } = await import("${{ github.workspace }}/.github/scripts/comment-on-new-pr.js");
            await commentOnNewPr({ context, github });
