name: Publish

on:
  push:
    branches:
      - main
      - canary

permissions:
	contents: write
	issues: write
	pull-requests: write

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Publish
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}

  update-canary:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [release]
    name: Update canary
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "canary"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Back-merge main into canary
        run: |
          git merge --ff-only origin/main
          git push
