name: Publish

on:
  push:
    branches:
      - main
      - canary

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Generate access token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Check out
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Publish
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}

  update-canary:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [release]
    name: Update canary
    runs-on: ubuntu-latest
    steps:
      - name: Generate access token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "canary"
          token: ${{ steps.generate-token.outputs.token }}

      - name: Back-merge main into canary
        run: |
          git merge --ff-only origin/main
          git push
