name: Release via comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  release_via_comment:
    name: Release via comment
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      github.event.issue.state == 'open' &&
      (
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'COLLABORATOR'
      ) &&
      contains(github.event.comment.body, '!release this')

    steps:
      - name: Generate access token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          # ensure branches share histories
          # see: https://github.com/actions/checkout/issues/125
          fetch-depth: 0

      - name: Verify PR and dispatch release workflow
        uses: actions/github-script@v7
        env:
          USER_NAME: ${{ vars.RELEASE_USER_NAME }}
          USER_EMAIL: ${{ vars.RELEASE_USER_EMAIL }}
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const { releaseViaComment } = await import("./.github/scripts/release-via-comment.js");
            await releaseViaComment({ context, core, exec, github });
