name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      acknowledge:
        description: "I understand that this action will publish everything on canary to the latest tag"
        required: true
        type: boolean

jobs:
  release:
    if: ${{ inputs.acknowledge }}
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Generate access token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "main"
          token: ${{ steps.generate-token.outputs.token }}

      - name: Merge canary into main
        run: |
          git merge --ff-only origin/canary
          git push
