name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      acknowledge:
        description: "I understand that this action will publish everything on canary to the latest tag"
        required: true
        type: boolean

jobs:
  release:
    if: ${{ inputs.acknowledge }}
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Generate access token
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
        id: generate-token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "main"
          token: ${{ steps.generate-token.outputs.token }}

      - name: Merge canary into main
        run: |
          git merge --ff-only origin/canary
          git push
